export default {
  //Plugin Names
  monitorPlugin: 'Monitor',
  controllerPlugin: 'Controller',
  webKitBrowserPlugin: 'WebKitBrowser',
  bluetoothControlPlugin: 'BluetoothControl',
  webKitImplementation: 'WebKitImplementation',
  deviceInfo: 'DeviceInfo',
  youTubePlugin: 'Cobalt',
  netFlixPlugin: 'Netflix',
  ocdmPlugin: 'OCDM',
  timeSyncPlugin: 'TimeSync',
  locationSyncPlugin: 'LocationSync',
  uxplugin: 'UX',
  volumeControl: 'VolumeControl',
  networkControlPlugin: 'NetworkControl',
  ocdmImplementation: 'OCDMImplementation',
  snapshotPlugin: 'Snapshot',
  ioconnector: 'IOConnector',
  webServerPlugin: 'WebServer',
  compositorPlugin: 'Compositor',
  webServerImplementation: 'WebServerImplementation',
  netflixImplementation: 'NetflixImplementation',
  youtubeImplementation: 'CobaltImplementation',
  powerPlugin: 'Power',
  provisioningPlugin: 'Provisioning',
  dhcpserver: 'DHCPServer',
  wifiControlPlugin: 'WifiControl',
  traceControlPlugin: 'TraceControl',
  firmwareUpgradePlugin: 'FirmwareControl',
  WPEProcess: 'WPEProcess',
  remoteControlPlugin: 'RemoteControl',
  invalidAddress: 'invalidstring',
  invalidPlugin: 'invalidplugin',
  displayInfo: 'DisplayInfo',

  hidden: 'hidden',
  visible: 'visible',

  //Plugin states
  activate: 'activate',
  deactivate: 'deactivate',
  resume: 'resumed',
  suspend: 'suspended',
  WPEFramework: 'WPEFramework',
  blankUrl: 'about:blank',
  youtubeLongMovieUrl: 'https://www.youtube.com/tv?v=kg3ElG-H7Wo&resume',
}
