export default {
  //Plugin Names
  monitorPlugin: 'Monitor',
  controllerPlugin: 'Controller',
  webKitBrowserPlugin: 'WebKitBrowser',
  bluetoothControlPlugin: 'BluetoothControl',
  webKitImplementation: 'WebKitImplementation',
  deviceInfo: 'DeviceInfo',
  youTubePlugin: 'Cobalt',
  netFlixPlugin: 'Netflix',
  ocdmPlugin: 'OCDM',
  timeSyncPlugin: 'TimeSync',
  locationSyncPlugin: 'LocationSync',
  uxplugin: 'UX',
  volumeControl: 'VolumeControl',
  ocdmImplementation: 'OCDMImplementation',
  snapshotPlugin: 'Snapshot',
  ioconnector: 'IOConnector',
  webServerPlugin: 'WebServer',
  compositorPlugin: 'Compositor',
  webServerImplementation: 'WebServerImplementation',
  netflixImplementation: 'NetflixImplementation',
  youtubeImplementation: 'CobaltImplementation',
  powerPlugin: 'Power',
  provisioningPlugin: 'Provisioning',
  dhcpserver: 'DHCPServer',
  traceControlPlugin: 'TraceControl',
  WPEProcess: 'WPEProcess',
  remoteControlPlugin: 'RemoteControl',
  invalidAddress: 'invalidstring',
  invalidPlugin: 'invalidplugin',
  displayInfo: 'DisplayInfo',

  hidden: 'hidden',
  visible: 'visible',

  //Plugin states
  activate: 'activate',
  deactivate: 'deactivate',
  resume: 'resumed',
  suspend: 'suspended',
  WPEFramework: 'WPEFramework',
  blankUrl: 'about:blank',
  youtubeLongMovieUrl: 'https://www.youtube.com/tv?v=kg3ElG-H7Wo&resume',
  // asset_vp9_1080p60: 'https://www.youtube.com/tv#/watch/video/idle?v=tMMVhUbwK6Q&resume',
  // asset_vp9_1080p30: 'https://www.youtube.com/tv#/watch/video/idle?v=TdpBRZ0dZhw&resume',
  // asset_avc_1080p30: 'https://www.youtube.com/tv#/watch/video/control?v=wggaaecdAac&resume',
  // asset_live_video: 'https://www.youtube.com/tv#/watch/video/idle?v=KGEekP1102g&resume'
}
